export const products = [
  {
    id: 1,
    price: 100,
    club: "Barcelona",
    player: "Messi",
    number: 10,
    title: "Messi's kit",
    description: "Messi's kit",
  },
  {
    id: 2,
    price: 100,
    club: "Barcelona",
    player: "Neymar",
    number: 11,
    title: "Neymar's kit",
    description: "Neymar's kit",
  },
  {
    id: 3,
    price: 100,
    club: "Barcelona",
    player: "Suarez",
    number: 9,
    title: "Suarez's kit",
    description: "Suarez's kit",
  },
  {
    id: 4,
    price: 100,
    club: "Barcelona",
    player: "Iniesta",
    number: 8,
    title: "Iniesta's kit",
    description: "Iniesta's kit",
  },
  {
    id: 5,
    price: 1,
    club: "Barcelona",
    player: "John",
    number: 99,
    title: "John's kit",
    description: "John's kit",
  },
];
